owner: swarmlet
repo: swarmlet-statuspage

sites:
  - name: Swarmlet website
    url: https://swarmlet.dev
  - name: Swarmlet install script
    url: https://get.swarmlet.dev

status-website:
  cname: status.swarmlet.dev
  logoUrl: https://github.com/swarmlet/swarmlet/raw/master/assets/logo.png
  name: Swarmlet Status
  introTitle: "**Swarmlet** is a self-hosted, open-source Platform as a Service"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
